# Generated by Django 4.2.5 on 2023-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
